-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.3.0.37 as of 11/1/2017 5:01 PM
-- Source Configuration: LSC_FORMS_PLT
-- License information--
-- Forms:
--   LSC_AddressValidationParameters, CustomerForms, Mobile
--   LSC_AddressValidationParameters, CustomerForms, Mobile_MS
--   LSC_AddressValidationParameters, CustomerForms, MoldingPack
--   LSC_AddressValidationParameters, CustomerForms, Transactional
--   LSC_AddressValidationParameters, CustomerForms, Transactional_MS
--
-- ** APPLY THIS SCRIPT TO THE TARGET APPLICATION DATABASE **
-------------------------------------------------------------------------------
DELETE FROM ModuleMembers WHERE ObjectName = N'LSC_AddressValidationParameters' AND ObjectType = 0 
  AND ModuleName = N'CustomerForms' AND OriginalModuleName = N'Mobile'
INSERT INTO ModuleMembers (ObjectType, ObjectName, ModuleName, OriginalModuleName, ModuleMemberSpec) 
  VALUES(0, N'LSC_AddressValidationParameters', N'CustomerForms', N'Mobile', N'!@6893@!::6482612da4a692e59811e4f4697f5d6639373049d99bc7c2f1a2c140754147f9' )
DELETE FROM ModuleMembers WHERE ObjectName = N'LSC_AddressValidationParameters' AND ObjectType = 0 
  AND ModuleName = N'CustomerForms' AND OriginalModuleName = N'Mobile_MS'
INSERT INTO ModuleMembers (ObjectType, ObjectName, ModuleName, OriginalModuleName, ModuleMemberSpec) 
  VALUES(0, N'LSC_AddressValidationParameters', N'CustomerForms', N'Mobile_MS', N'!@6893@!::0c19c8f702bec1d1ff6b5832dc1dbec35c32b0abe856e373781243a9fec1e676' )
DELETE FROM ModuleMembers WHERE ObjectName = N'LSC_AddressValidationParameters' AND ObjectType = 0 
  AND ModuleName = N'CustomerForms' AND OriginalModuleName = N'MoldingPack'
INSERT INTO ModuleMembers (ObjectType, ObjectName, ModuleName, OriginalModuleName, ModuleMemberSpec) 
  VALUES(0, N'LSC_AddressValidationParameters', N'CustomerForms', N'MoldingPack', N'!@6893@!::74db1fc94991f1020a32c1b2a14fea020dfbcf91d87d5a55e3749ef7c3bce66c' )
DELETE FROM ModuleMembers WHERE ObjectName = N'LSC_AddressValidationParameters' AND ObjectType = 0 
  AND ModuleName = N'CustomerForms' AND OriginalModuleName = N'Transactional'
INSERT INTO ModuleMembers (ObjectType, ObjectName, ModuleName, OriginalModuleName, ModuleMemberSpec) 
  VALUES(0, N'LSC_AddressValidationParameters', N'CustomerForms', N'Transactional', N'!@6893@!::84f2c6c1642d976d38a005b03942951f1329d97f09f11d6795c16b051f914985' )
DELETE FROM ModuleMembers WHERE ObjectName = N'LSC_AddressValidationParameters' AND ObjectType = 0 
  AND ModuleName = N'CustomerForms' AND OriginalModuleName = N'Transactional_MS'
INSERT INTO ModuleMembers (ObjectType, ObjectName, ModuleName, OriginalModuleName, ModuleMemberSpec) 
  VALUES(0, N'LSC_AddressValidationParameters', N'CustomerForms', N'Transactional_MS', N'!@6893@!::f76ae9f6f5fe787a993f2111927eafc82bce23ae9ce7c1a01d8d971f72998bdd' )
